from tkinter import*
class System(Exception):
    def exp(self):
        print("Enter the correct username or password")
def press():
    n=e.get()+e1.get()
    try:
        if e.get()=="abc" and e1.get()=="1234":
            details()
        else:
            raise System()
    except System as a:
        print(a.exp())
    print(n)
root=Tk()
root.title("my first GUI")
root.configure(background="GREEN")
root.geometry("400x400")
l=Label(text="REIMBURSEMENT SYSTEM",bg="white",fg="red",relief=RAISED).grid(row=1,column=12)
l1=Label(text="LOGIN",bg="white",fg="red",relief=RAISED).grid(row=8,column=5)
l2=Label(root,text="username").grid(row=10,column=5)
e=Entry(root)
e.grid(row=10,column=8)
l3=Label(text="password").grid(row=12,column=5)
e1=Entry(root)
e1.grid(row=12,column=8)
b=Button(text="login",command=press)
b.grid(row=14,column=5)
def details():
    root1=Tk()
    root1.title("CHOOSE ONE")
    root1.configure(background="BLUE")
    l=Label(root1,text="REIMBURSEMENT SYSTEM",bg="white",fg="red",relief=RAISED).grid(row=1,column=12)
    b1=Button(root1,text="New User",command=click1)
    b1.grid(row=4,column=12)
    b2=Button(root1,text="Display",command=click2)
    b2.grid(row=12,column=12)
def click1():
    root3=Tk()
    root3.title("NEW USER DETAILS")
    def add1():
        print("****NEW USER DETAILS****")
        print("USERNAME:",e.get(),"USERID:",e1.get(),"REQUEST:",e2.get(),"DESIGNATION:",e3.get(),"DATEOFSUBMIT:",e4.get())
    root3.configure(background="BLUE")
    k=Label(root3,text="NEW USER",bg="white",fg="red",relief=RAISED).grid(row=1,column=12)
    l=Label(root3,text="USERNAME",bg="white",fg="red",relief=RAISED).grid(row=3,column=5)
    e=Entry(root3)
    e.grid(row=3,column=10)
    l1=Label(root3,text="USERID",bg="white",fg="red",relief=RAISED).grid(row=5,column=5)
    e1=Entry(root3)
    e1.grid(row=5,column=10)
    l2=Label(root3,text="REQUEST",bg="white",fg="red",relief=RAISED).grid(row=7,column=5)
    e2=Entry(root3)
    e2.grid(row=7,column=10)
    l3=Label(root3,text="DESIGNATION",bg="white",fg="red",relief=RAISED).grid(row=9,column=5)
    e3=Entry(root3)
    e3.grid(row=9,column=10)
    l4=Label(root3,text="DATEOFSUBMIT",bg="white",fg="red",relief=RAISED).grid(row=10,column=5)
    e4=Entry(root3)
    e4.grid(row=10,column=10)
    b=Button(root3,text="ADD",command=add1)
    b.grid(row=15,column=12)
    messagebox.showinfo("Success")
def click2():
    root5=Tk()
    root5.title("USER DETAILS")
    def add3():
        print("****USER DETAILS****")
        print("USER NAME:",e.get(),"USER ID:",e1.get(),"ADDRESS:",e2.get(),"PHONE NUMBER:",e3.get())
    root5.configure(background="BLUE")
    k=Label(root5,text="NEW SUBJECT",bg="BLUE",fg="red",relief=RAISED).grid(row=1,column=12)
    l=Label(root5,text="USER NAME",bg="white",fg="red",relief=RAISED).grid(row=3,column=5)
    e=Entry(root5)
    e.grid(row=3,column=10)
    l1=Label(root5,text="USER ID",bg="white",fg="red",relief=RAISED).grid(row=5,column=5)
    e1=Entry(root5)
    e1.grid(row=5,column=10)
    l=Label(root5,text="ADDRESS",bg="white",fg="red",relief=RAISED).grid(row=7,column=5)
    e2=Entry(root5)
    e2.grid(row=7,column=10)
    l0=Label(root5,text="PHONE NUMBER",bg="white",fg="red",relief=RAISED).grid(row=9,column=5)
    e3=Entry(root5)
    e3.grid(row=9,column=10)
    b=Button(root5,text="DISPLAY",command=add3)
    b.grid(row=12,column=12)
