from tkinter import*
def click1():
    root=Tk()
    root.title("NEW USER DETAILS")
    def add1():
        print("****NEW USER DETAILS****")
        print("USERNAME:",e.get(),"USERID:",e1.get(),"REQUEST:",e2.get(),"DESIGNATION:",e3.get(),"DATEOFSUBMIT:",e4.get())
    root.configure(background="BLUE")
    k=Label(root,text="NEW USER",bg="white",fg="red",relief=RAISED).grid(row=1,column=12)
    l=Label(root,text="USERNAME",bg="white",fg="red",relief=RAISED).grid(row=3,column=5)
    e=Entry(root)
    e.grid(row=3,column=10)
    l1=Label(root,text="USERID",bg="white",fg="red",relief=RAISED).grid(row=5,column=5)
    e1=Entry(root)
    e1.grid(row=5,column=10)
    l2=Label(root,text="REQUEST",bg="white",fg="red",relief=RAISED).grid(row=7,column=5)
    e2=Entry(root)
    e2.grid(row=7,column=10)
    l3=Label(root,text="DESIGNATION",bg="white",fg="red",relief=RAISED).grid(row=9,column=5)
    e3=Entry(root)
    e3.grid(row=9,column=10)
    l4=Label(root,text="DATEOFSUBMIT",bg="white",fg="red",relief=RAISED).grid(row=10,column=5)
    e4=Entry(root)
    e4.grid(row=10,column=10)
    b=Button(root,text="ADD",command=add1)
    b.grid(row=15,column=12)
click1()
